@extends('layouts')

@section('isi')
  <div class="container content-box " style="margin-top: 120px;">
    <h4>Apa itu Sewa Sewo?</h4>
    <hr>
    <p> Website ini dibuat oleh Fasha, Bagas, dan Ihza sebagai cara memperoleh nilai mata kuliah pemweb dan pbd. Fungsi dari website yang kami buat ini adalah untuk melakukan booking terhadap fasilitas/lapangan olahraga. Pengguna dapat membuat akun baik untuk melakukan penyewaan atau bahkan membuat toko untuk menjadi penyedia sewaan.</p>
    <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod quisquam labore laudantium tempore iure doloribus explicabo aspernatur velit itaque animi unde obcaecati, doloremque, eveniet dolores tempora libero sunt sint vitae veniam dolor. A quod exercitationem enim repellendus laboriosam reiciendis ea, at iste excepturi earum! At libero distinctio, ex provident ea pariatur accusamus culpa impedit architecto repudiandae consectetur error maxime ducimus id commodi? Non eaque quibusdam perferendis perspiciatis sapiente totam dolore voluptate quas, autem enim exercitationem illo explicabo at, cum nulla. Tempore quia veniam nobis vitae quam ut voluptate tempora expedita sunt eaque sint a eveniet eligendi et consequatur hic iste ducimus omnis exercitationem libero assumenda, optio quod reprehenderit. Magnam eaque est eos blanditiis qui, enim neque ab aut corrupti tempore distinctio cumque pariatur, doloribus maiores et maxime, accusantium provident soluta optio aliquam atque sapiente modi nam voluptates? Consequatur repellendus distinctio placeat assumenda excepturi alias laudantium sit, ut iste doloremque, rem voluptatibus accusamus exercitationem sed dignissimos quam magnam expedita at reiciendis veniam sequi quae, quibusdam magni. Perspiciatis accusantium blanditiis id architecto molestias quos, alias dolor. Cupiditate vero asperiores adipisci quo perspiciatis maiores, ipsa voluptatum! Reprehenderit sunt, fuga dicta inventore, mollitia non iure sit, incidunt ipsa cum fugit animi quis. A hic dolorem expedita ipsum ullam, cumque repellat. Dignissimos mollitia odio autem numquam nam ea delectus, aspernatur molestias nesciunt expedita beatae assumenda quia, dolore sequi voluptates sunt deserunt libero, nulla facilis. Ipsa porro eligendi, consequatur nihil odit praesentium quidem voluptatibus, eos accusamus maiores culpa? Aperiam impedit quam harum iusto, dolore velit rerum ex et. Porro exercitationem harum ipsam ipsum esse magnam culpa quibusdam distinctio error nisi corporis laborum architecto vel laboriosam eaque, non quam rem a enim dolor eos, totam magni modi laudantium. Qui laboriosam iusto nam eos culpa soluta fugiat doloribus quas voluptate minus voluptatibus mollitia illo, placeat a maiores dolor.</p>
    <br>
    <hr>
    <h4>Siapakah Pembuat Sewa Sewo?</h4>
    <hr>
    <p> Website ini dibuat oleh Fasha, Bagas, dan Ihza sebagai cara memperoleh nilai mata kuliah pemweb dan pbd. Fungsi dari website yang kami buat ini adalah untuk melakukan booking terhadap fasilitas/lapangan olahraga. Pengguna dapat membuat akun baik untuk melakukan penyewaan atau bahkan membuat toko untuk menjadi penyedia sewaan.</p>
    <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod quisquam labore laudantium tempore iure doloribus explicabo aspernatur velit itaque animi unde obcaecati, doloremque, eveniet dolores tempora libero sunt sint vitae veniam dolor. A quod exercitationem enim repellendus laboriosam reiciendis ea, at iste excepturi earum! At libero distinctio, ex provident ea pariatur accusamus culpa impedit architecto repudiandae consectetur error maxime ducimus id commodi? Non eaque quibusdam perferendis perspiciatis sapiente totam dolore voluptate quas, autem enim exercitationem illo explicabo at, cum nulla. Tempore quia veniam nobis vitae quam ut voluptate tempora expedita sunt eaque sint a eveniet eligendi et consequatur hic iste ducimus omnis exercitationem libero assumenda, optio quod reprehenderit. Magnam eaque est eos blanditiis qui, enim neque ab aut corrupti tempore distinctio cumque pariatur, doloribus maiores et maxime, accusantium provident soluta optio aliquam atque sapiente modi nam voluptates? Consequatur repellendus distinctio placeat assumenda excepturi alias laudantium sit, ut iste doloremque, rem voluptatibus accusamus exercitationem sed dignissimos quam magnam expedita at reiciendis veniam sequi quae, quibusdam magni. Perspiciatis accusantium blanditiis id architecto molestias quos, alias dolor. Cupiditate vero asperiores adipisci quo perspiciatis maiores, ipsa voluptatum! Reprehenderit sunt, fuga dicta inventore, mollitia non iure sit, incidunt ipsa cum fugit animi quis. A hic dolorem expedita ipsum ullam, cumque repellat. Dignissimos mollitia odio autem numquam nam ea delectus, aspernatur molestias nesciunt expedita beatae assumenda quia, dolore sequi voluptates sunt deserunt libero, nulla facilis. Ipsa porro eligendi, consequatur nihil odit praesentium quidem voluptatibus, eos accusamus maiores culpa? Aperiam impedit quam harum iusto, dolore velit rerum ex et. Porro exercitationem harum ipsam ipsum esse magnam culpa quibusdam distinctio error nisi corporis laborum architecto vel laboriosam eaque, non quam rem a enim dolor eos, totam magni modi laudantium. Qui laboriosam iusto nam eos culpa soluta fugiat doloribus quas voluptate minus voluptatibus mollitia illo, placeat a maiores dolor.</p>

    
    <!-- Your page content goes here -->
  </div>
@endsection
